version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    volumes:
      - ./MyVendor.Ticket:/var/www/html:ro
    networks:
      - app-network

  frontend:
    build: ./createxyz-project
    ports:
      - "3000:80"
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build: ./php-fpm
    volumes:
      - ./MyVendor.Ticket:/var/www/html
    environment:
      TKT_DB_HOST: mysql
      TKT_DB_PORT: 3306
      TKT_DB_NAME: ticket
      TKT_DB_USER: root
      TKT_DB_PASS: root
      TKT_DB_DSN: "mysql:host=mysql;port=3306;dbname=ticket;charset=utf8"
    networks:
      - app-network

  mysql:
    image: mysql:8.2
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # bearsunday:
  #   build: ./MyVendor.Ticket  # 必要に応じて、こちらもビルド方式に変更できます。現状の用途に合わせてください。
  #   networks:
  #     - app-network
  #
volumes:
  mysql_data:

networks:
  app-network:

