version: '3.8'

services:
  frontend:
    build: ./createxyz-project
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./MyVendor.Ticket
    ports:
      - "8080:80"
    volumes:
      - ./MyVendor.Ticket:/var/www/html
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ticket
      DB_USERNAME: yasu
      DB_PASSWORD: pass
    depends_on:
      - mysql

  mysql:
    image: mysql:8.2
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket
      MYSQL_USER: yasu
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

